query ProductsFromCategory($categoryName: String!) {
    category(query: {
        category_name: $categoryName
    }) {
        products {
            id
            name
            unique_name
            display_description
            price
            stock
            images {
                display_image
                alt
            }
            categories {
                category_name	
            }
            promo {
                promotion_percentage
            }
        }
    }
}