query productHot {
    products {
        records {
            id
            name
            unique_name
            display_description
            attributes {
                attribute_name
            }
            seller {
                    seller_name
            }
            brand {
                brand_name
            }
            images {
                id
            }
            categories {
                category_name	
            }
            promotions {
                promotion_percentage
                is_active
            }
            promo {
                promotion_percentage
            }
            reviews {
                review
            }
            tags {
                tag_name
            }
            variations {
                variation_name
                variation_value
            }
        }
    }
}